export const FETCH_COUNTERS = 'FETCH_COUNTERS';
export const FETCH_COUNTERS_SUCCESS = 'FETCH_COUNTERS_SUCCESS';

export const INCREMENT = 'INCREMENT';

export const DECREMENT = 'DECREMENT';

export const DELETE = 'DELETE';
