export const FETCH_COUNTERS = 'FETCH_COUNTERS';
export const FETCH_COUNTERS_SUCCESS = 'FETCH_COUNTERS_SUCCESS';

export const INCREMENT = 'INCREMENT';
export const INCREMENT_SUCCESS = 'INCREMENT_SUCCESS';

export const DECREMENT = 'DECREMENT';
export const DECREMENT_SUCCESS = 'DECREMENT_SUCCESS';

export const DELETE = 'DELETE';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
